services:
  rucq-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_DEV_USER=${VITE_DEV_USER}
    ports:
      - '5173:80'
    restart: unless-stopped
