name: main

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: rucq-ui

jobs:
  build-image:
    name: Build Docker Image and Push to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Show available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/traptitech/${{ env.IMAGE_NAME }}:main
          cache-from: type=registry,ref=ghcr.io/traptitech/${{ env.IMAGE_NAME }}:buildcache

  run-manifest-renovate:
    name: Run Renovate on manifest
    runs-on: ubuntu-latest
    needs: [build-image]
    permissions:
      contents: read
      actions: write
    steps:
      - run: 'gh api --method POST -H "Accept: application/vnd.github+json" /repos/traPtitech/manifest/actions/workflows/renovate.yaml/dispatches -f "ref=main"'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
