name: Renovate Config Validator

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/renovate-bot.json5
      - .github/renovate.json
      - .github/renovate/**
      - .github/workflows/renovate-config-validator-ci.yaml

permissions:
  contents: read

jobs:
  renovate-config-validator:
    timeout-minutes: 10
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Validate Renovate global configuration
        run: npx --yes --package renovate@43.261.4 -- renovate-config-validator --strict .github/renovate-bot.json5

      - name: Validate Renovate repository configuration
        run: npx --yes --package renovate@43.261.4 -- renovate-config-validator --strict --no-global .github/renovate.json .github/renovate/*.json5
